function wig_logged(logfile, fcnName)
%WIG_LOGGED  运行指定函数，并把全部文本输出（UTF-8）写入日志文件
%
%   wig_logged(logfile, 'run_xx_yyy_body')
%
%   控制台输出受 Windows 代码页影响可能出现乱码，日志文件始终为 UTF-8，
%   便于后续查看与归档。
%   异常处理：在 evalc 内部用 try/catch 包裹被调用函数，因此即使中途报错，
%   【报错前已经产生的全部输出】也会被完整保留，并附上异常标识、调用栈
%   与 cause 链（Simulink 的 S-Function 错误常把真实原因放在 cause 中）。

cmd = sprintf([ ...
    'try\n' ...
    '    %s;\n' ...
    'catch ME\n' ...
    '    disp(''''); disp(''!!!!!! 运行异常 !!!!!!'');\n' ...
    '    disp(getReport(ME, ''extended'', ''hyperlinks'', ''off''));\n' ...
    '    c = ME.cause; lvl = 1;\n' ...
    '    while ~isempty(c) && lvl <= 6\n' ...
    '        for j = 1:numel(c)\n' ...
    '            fprintf(''  [原因 %%d-%%d] %%s: %%s\\n'', lvl, j, c{j}.identifier, c{j}.message);\n' ...
    '        end\n' ...
    '        nxt = {};\n' ...
    '        for j = 1:numel(c)\n' ...
    '            if ~isempty(c{j}.cause), nxt = [nxt, c{j}.cause]; end\n' ...
    '        end\n' ...
    '        c = nxt; lvl = lvl + 1;\n' ...
    '    end\n' ...
    'end\n'], fcnName);

s = evalc(cmd);

fid = fopen(logfile, 'w', 'n', 'UTF-8');
if fid > 0
    fprintf(fid, '%s', s);
    fclose(fid);
end

try
    fprintf('%s', s);
catch
end
fprintf('\n[日志已写入] %s\n', logfile);

end
